apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-alert-rules
  namespace: monitoring
  labels:
    prometheus: prometheus
    role: alert-rules
spec:
  groups:
  - name: service-health
    rules:
    - alert: ServiceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Service {{ $labels.job }} is down"
        description: "Service {{ $labels.job }} has been down for more than 1 minute"
    
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (job) / sum(rate(http_requests_total[5m])) by (job) > 0.05
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High error rate for {{ $labels.job }}"
        description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.job }}"
    
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job)) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time for {{ $labels.job }}"
        description: "95th percentile response time is {{ $value }}s for {{ $labels.job }}"

  - name: infrastructure
    rules:
    - alert: HighCPUUsage
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on {{ $labels.instance }}"
        description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"
    
    - alert: HighMemoryUsage
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage on {{ $labels.instance }}"
        description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"
    
    - alert: HighDiskUsage
      expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High disk usage on {{ $labels.instance }}"
        description: "Disk usage is {{ $value }}% on {{ $labels.instance }}"

  - name: database
    rules:
    - alert: DatabaseHighConnections
      expr: pg_stat_database_numbackends > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High database connections"
        description: "Database has {{ $value }} active connections"
    
    - alert: RedisHighMemoryUsage
      expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High Redis memory usage"
        description: "Redis memory usage is {{ $value }}%"

  - name: security
    rules:
    - alert: HighFailedLogins
      expr: rate(auth_failures_total[5m]) > 10
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "High number of failed login attempts"
        description: "{{ $value }} failed login attempts per second"
    
    - alert: SuspiciousActivity
      expr: rate(security_events_total[5m]) > 5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Suspicious activity detected"
        description: "{{ $value }} security events per second"

  - name: storage
    rules:
    - alert: StorageHighUsage
      expr: image_storage_bytes_used / image_storage_bytes_total * 100 > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High storage usage"
        description: "Storage usage is {{ $value }}%"
    
    - alert: ImageServiceDown
      expr: up{job="image-service"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Image service is down"
        description: "Image service has been down for more than 1 minute"

  - name: kubernetes
    rules:
    - alert: PodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total[15m]) > 5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Pod {{ $labels.pod }} is crash looping"
        description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 15 minutes"
    
    - alert: PodNotReady
      expr: kube_pod_status_phase{phase!="Running"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod {{ $labels.pod }} is not ready"
        description: "Pod {{ $labels.pod }} is in {{ $labels.phase }} state" 