apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: applications
type: Opaque
data:
  jwt-secret: eW91ci1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW5z  # your-secret-key-for-jwt-tokens in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: applications
type: Opaque
data:
  api-key: YXBpLWtleS1mb3ItZXh0ZXJuYWwtc2VydmljZXM=  # api-key-for-external-services in base64
  encryption-key: ZW5jcnlwdGlvbi1rZXktZm9yLXNlbnNpdGl2ZS1kYXRh  # encryption-key-for-sensitive-data in base64 